### ISSUE TITLE
ModuleNotFoundError: No module named 'pkg_resources'

### ISSUE THREAD

**Issue by abhishekchitwar** [ansys/ansys-tools-visualization-interface#45]
### 🔍 Before submitting the issue

- [X] I have searched among the existing issues
- [X] I am using a Python virtual environment

### 🐞 Description of the bug

Failed to run the following example from documentation

```python 
import pyvista as pv
from ansys.tools.visualization_interface import Plotter

mesh = pv.Cube()
# Create a plotter
pl = Plotter()
# Add the mesh to the plotter
pl.plot(mesh)
# Show the plotter
pl.show()
```
``` text
Traceback (most recent call last):
  File "d:\Research\visualization\ansys-tools-visualization-interface\visualization-interface.py", line 2, in <module>
    from ansys.tools.visualization_interface import Plotter
  File "D:\Repos\ansys-tools-visualization-interface\src\ansys\tools\visualization_interface\__init__.py", line 25, in <module>
    import pkg_resources
ModuleNotFoundError: No module named 'pkg_resources'
```

### 📝 Steps to reproduce

1. Install local development version with virtual environment.
2. run the code snippet provided with description section.

### 💻 Which operating system are you using?

Windows

### 📀 Which ANSYS version are you using?

NA

### 🐍 Which Python version are you using?

3.12

### 📦 Installed packages

```shell
about-time==4.2.1
aiohttp==3.9.5
aiosignal==1.3.1
alive-progress==3.1.5
ansys-api-fluent==0.3.22
ansys-api-platform-instancemanagement==1.1.0
ansys-fluent-core==0.20.1
ansys-fluent-visualization==0.9.0
ansys-platform-instancemanagement==1.1.2
-e git+https://github.com/ansys/ansys-tools-visualization-interface@92495cf670d3d75c5c5a288ea50629acc6f56ecf#egg=ansys_tools_visualization_interface
ansys-units==0.3.2
attrs==23.2.0
beartype==0.17.2
certifi==2024.2.2
charset-normalizer==3.3.2
contourpy==1.2.1
cycler==0.12.1
docker==6.1.3
fonttools==4.51.0
frozenlist==1.4.1
grapheme==0.6.0
grpcio==1.63.0
grpcio-health-checking==1.48.2
idna==3.7
importlib_metadata==7.1.0
kiwisolver==1.4.5
lxml==4.9.4
matplotlib==3.9.0
more-itertools==10.2.0
msgpack==1.0.8
multidict==6.0.5
numpy==1.26.4
packaging==24.0
pandas==1.5.3
pillow==10.3.0
platformdirs==3.11.0
pooch==1.8.1
protobuf==3.20.3
psutil==5.9.8
pyparsing==3.1.2
PySide6==6.7.0
PySide6_Addons==6.7.0
PySide6_Essentials==6.7.0
python-dateutil==2.9.0.post0
pytz==2024.1
pyvista==0.43.8
pyvistaqt==0.11.0
pywin32==306
PyYAML==6.0.1
QtPy==2.4.1
requests==2.31.0
scooby==0.10.0
shiboken6==6.7.0
six==1.16.0
trame==3.6.0
trame-client==3.0.3
trame-server==3.0.0
trame-vtk==2.8.8
trame-vuetify==2.5.0
urllib3==2.2.1
vtk==9.3.0
websocket-client==1.8.0
websockets==12.0
wslink==2.0.2
yarl==1.9.4
zipp==3.18.2
```

**Comment by abhishekchitwar** [comment]
Not sure what is the root cause of the issue. However, reinstalling the module with a new virtual environment resolved the issue.

**Comment by RobPasMue** [comment]
Python 3.12 does not provide ``pkg_resources`` by default. If it is not included as a dependency, it should be added.

See https://docs.python.org/3/whatsnew/3.12.html#summary-release-highlights and search for "setuptools" or "pkg_resources"

**Comment by AlejandroFernandezLuces** [comment]
This was fixed by https://github.com/ansys/ansys-tools-visualization-interface/pull/51 , I was getting the project version the wrong way

**Comment by AlejandroFernandezLuces** [comment]
And thanks for opening the issue @abhishekchitwar 😄
